# Select a specfic if possible, otherwise use a minimal image that gets you close
FROM node:16-alpine

# Expose port
EXPOSE 9090

# Start
WORKDIR /workspace/frontend
# COPY . .
ENTRYPOINT [ "npm", "run", "start" ]
# CMD ["sleep", "infinity"]
