version: '3.8'
services:
  my-app-frontend:
    build: ./frontend
    volumes:
      - eggshell-volume:/home/app
    container_name: my-app-frontend
    networks:
      - eggshell-network
    ports:
      - 8080:8080
    # Needed to keep the container from exiting
    stdin_open: true

  my-app-backend:
    build: ./backend
    volumes:
      - eggshell-volume:/home/app
    container_name: eggshell-backend
    networks:
      - eggshell-network
    ports:
      - 3000:3000

volumes:
  eggshell-volume:
    external: true

networks:
  eggshell-network:
    external: true
