version: "3.9"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ../.devcontainer/Dockerfile.dev-container
    volumes:
      # - .:/app
      - ./frontend:/workspace:cached
    container_name: frontend-container
    # networks:
    #   - eggshell-network
    ports:
      - 8080:8080
    # Needed to keep the container from exiting
    # stdin_open: true
    links:
      - backend
    working_dir: /workspace
    entrypoint: ["npm", "run", "start"]

  backend:
    build:
      context: ./backend
      dockerfile: ../.devcontainer/Dockerfile.dev-container
    volumes:
      # - .:/app
      - ./backend:/workspace:cached
    container_name: backend-container
    # networks:
    #   - eggshell-network
    ports:
      - 3000:3000
    working_dir: /workspace
    entrypoint: ["npm", "run", "start"]
# volumes:
#   eggshell-volume:
#     external: true

# networks:
#   eggshell-network:
#     external: true
