# Select a specfic if possible, otherwise use a minimal image that gets you close
FROM node:16-alpine

# Expose port
EXPOSE 3000

# Start
WORKDIR /app
# COPY . .
ENTRYPOINT [ "npm", "run", "start" ]
# CMD ["sleep", "infinity"]

