# Select a specfic if possible, otherwise use a minimal image that gets you close
FROM node:16-alpine

# Expose port
EXPOSE 5000

# Start
WORKDIR /app
COPY ./src .
ENTRYPOINT [ "node", "index.js" ]
# CMD ["sleep", "infinity"]

