apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-experiment-preview
  annotations:
    ingress.kubernetes.io/proxy-body-size: 100M
    ingress.kubernetes.io/app-root: /
spec:
  rules:
  - host: hello.backend-experiment-preview.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: backend-experiment-preview
            port:
              number: 5000
  ingressClassName: nginx