apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ template "backend-experiment.fullname" . }}
  labels:
    app: {{ template "backend-experiment.name" . }}
    chart: {{ template "backend-experiment.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    canary:
      experimentService: {{ template "backend-experiment.fullname" . }}-preview
      steps:
      - experiment:
          duration: 60s
          templates:
          - name: experiment
            specRef: canary
          analyses:
          - name: load-test
            templateName: http-benchmark
            args:
            - name: host
              value: {{ template "backend-experiment.fullname" . }}-preview
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: {{ template "backend-experiment.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "backend-experiment.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
