apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-canary-active
spec:
  rules:
  - host: hello.backend-canary-active.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: backend-canary-active
            port:
              number: 5000
  ingressClassName: nginx