apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-canary-preview
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: backend-canary-preview
            port:
              number: 5000