# Note: You can use any Debian/Ubuntu based image you want. 
FROM mcr.microsoft.com/devcontainers/typescript-node:16

# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>

# Copy the full repository into the /workspaces directory
# This will then get mounted into the shared app volume
# WORKDIR /workspaces
# COPY . .