name: Pipeline workflow

on:
  push:
    branches: ["main"]

jobs:
  pipeline-job:
    runs-on: ubuntu-latest
    env:
      PROJECT_DIR: backend
    steps:
      # - uses: docker://mcr.microsoft.com/devcontainers/typescript-node:16
      - uses: actions/checkout@v3

      - name: Config
        run: |
          cat ./backend/.env >> $GITHUB_ENV
          docker info
          docker version
          docker compose version
          docker-compose -v

      - name: Registry login
        run: |
          export DOCKER_PASSWORD="${{secrets.DOCKER_PASSWORD}}"
          ./agnostic-pipeline/stages/01_login.sh

      - name: Ci
        run: |
          ./agnostic-pipeline/stages/01_ci.sh

      - name: Build
        run: |
          ./agnostic-pipeline/stages/02_build.sh

      - name: Test
        run: |
          ./agnostic-pipeline/stages/03_test.sh

      - name: Archive
        run: |
          ./agnostic-pipeline/stages/04_archive.sh

      - name: Deploy
        run: |
          export SSH_PRIVATE_KEY="${{secrets.SSH_PRIVATE_KEY}}"
          ./agnostic-pipeline/stages/05_deploy.sh

      - name: Archive CI
        run: |
          ./agnostic-pipeline/stages/06_archive-ci.sh
