name: Pipeline workflow

on:
  push:
    branches: ["main"]

jobs:
  pipeline-job:
    runs-on: ubuntu-latest
    env:
      PROJECT_DIR: backend
    steps:
      # - uses: docker://mcr.microsoft.com/devcontainers/typescript-node:16
      - uses: actions/checkout@v3

      # - name: Ci
      #   run: |
      #     ./agnostic-pipeline/stages/ci-step.sh

      # - name: Config
      #   run: |
      #     cat ./backend/.env >> $GITHUB_ENV
      #     export AWS_ACCESS_KEY_ID="${{secrets.AWS_ACCESS_KEY_ID}}"
      #     export AWS_SECRET_ACCESS_KEY="${{secrets.AWS_SECRET_ACCESS_KEY}}"
      #     export YC_TOKEN="${{secrets.YC_TOKEN}}"
      #     export YC_CLOUD_ID="${{secrets.YC_CLOUD_ID}}"
      #     export YC_FOLDER_ID="${{secrets.YC_FOLDER_ID}}"
      #     ./agnostic-pipeline/stages/config-step.sh

      # - name: Registry login
      #   run: |
      #     export DOCKER_PASSWORD="${{secrets.DOCKER_PASSWORD}}"
      #     ./agnostic-pipeline/stages/01_login.sh


      # - name: Build
      #   run: |
      #     ./agnostic-pipeline/stages/02_build.sh

      # - name: Test
      #   run: |
      #     ./agnostic-pipeline/stages/03_test.sh

      # - name: Archive
      #   run: |
      #     ./agnostic-pipeline/stages/04_archive.sh

      # - name: Deploy
      #   run: |
      #     export SSH_PRIVATE_KEY="${{secrets.SSH_PRIVATE_KEY}}"
      #     ./agnostic-pipeline/stages/deploy-step.sh

      # - name: Archive CI
      #   run: |
      #     ./agnostic-pipeline/stages/06_archive-ci.sh
