apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: backend
    server: { { .Values.spec.destination.server } }
  project: default
  source:
    path: backend/helm
    repoURL: { { .Values.spec.source.repoURL } }
    targetRevision: { { .Values.spec.source.targetRevision } }
